# Generated by Django 2.1.5 on 2019-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
                ('stream', models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science Engineering')], max_length=4)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
